language: generic

services:
  - docker

install:
  - docker-compose build

before_script:
  - docker-compose -f docker-compose.yml up

script:
  - docker-compose exec web rake --trace rubocop db:migrate test:skip_visuals

after_script:
- docker-compose down

notifications:
  email: false
